// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$default = {
  disabled: false
};

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* No side effect */
