// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var Caml_option = require("@rescript/std/lib/js/caml_option.js");
var DomHelpers = require("dom-helpers");

function addClass(node, classes) {
  if (node === undefined) {
    return ;
  }
  if (classes === undefined) {
    return ;
  }
  var node$1 = Caml_option.valFromOption(node);
  return Belt_Array.forEach(classes.split(" "), (function (c) {
                DomHelpers.addClass(node$1, c);
                
              }));
}

function removeClass(node, classes) {
  if (node === undefined) {
    return ;
  }
  if (classes === undefined) {
    return ;
  }
  var node$1 = Caml_option.valFromOption(node);
  return Belt_Array.forEach(classes.split(" "), (function (c) {
                DomHelpers.removeClass(node$1, c);
                
              }));
}

exports.addClass = addClass;
exports.removeClass = removeClass;
/* dom-helpers Not a pure module */
