// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function pluralize(quantity, singular, plural) {
  if (quantity > 1) {
    return plural;
  } else {
    return singular;
  }
}

exports.pluralize = pluralize;
/* No side effect */
