// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");
var React = require("react");

var setSelectionContext = React.createContext(undefined);

var selectionContext = React.createContext(undefined);

var screenContext = React.createContext(undefined);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = screenContext.Provider;

var ScreenContextProvider = {
  makeProps: makeProps,
  make: make
};

function makeProps$1(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make$1 = setSelectionContext.Provider;

var SetSelectionContextProvider = {
  makeProps: makeProps$1,
  make: make$1
};

function makeProps$2(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make$2 = selectionContext.Provider;

var SelectionContextProvider = {
  makeProps: makeProps$2,
  make: make$2
};

function SelectContext(Props) {
  var componentId = Props.componentId;
  var children = Props.children;
  var match = React.useState(function () {
        
      });
  var setSelection = match[1];
  var setSelection$1 = function (newSelection) {
    return Curry._1(setSelection, (function (param) {
                  return newSelection;
                }));
  };
  return React.createElement(make, makeProps(componentId, React.createElement(make$1, makeProps$1(setSelection$1, React.createElement(make$2, makeProps$2(match[0], children, undefined)), undefined)), undefined));
}

function noopPressed(param) {
  return false;
}

function noopSetPressed(param, param$1) {
  
}

var make$3 = SelectContext;

exports.setSelectionContext = setSelectionContext;
exports.selectionContext = selectionContext;
exports.screenContext = screenContext;
exports.ScreenContextProvider = ScreenContextProvider;
exports.SetSelectionContextProvider = SetSelectionContextProvider;
exports.SelectionContextProvider = SelectionContextProvider;
exports.make = make$3;
exports.noopPressed = noopPressed;
exports.noopSetPressed = noopSetPressed;
/* setSelectionContext Not a pure module */
