// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function initValue_1(param) {
  
}

var initValue = [
  undefined,
  initValue_1
];

var context = React.createContext(initValue);

function useContext(param) {
  return React.useContext(context);
}

exports.initValue = initValue;
exports.context = context;
exports.useContext = useContext;
/* context Not a pure module */
