// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isMounting(param) {
  return param.isMounting;
}

function appear(param) {
  return param.appear;
}

function enter(param) {
  return param.enter;
}

function exit(param) {
  return param.exit;
}

var Config = {
  isMounting: isMounting,
  appear: appear,
  enter: enter,
  exit: exit
};

function reducer(param, action) {
  return action._0;
}

var initialState;

exports.Config = Config;
exports.initialState = initialState;
exports.reducer = reducer;
/* No side effect */
