// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");
var React = require("react");
var TransitionGroupContext$negRescriptTransitionGroup = require("./TransitionGroupContext.bs.js");

function isMounting(state) {
  return state.isMounting;
}

function useIsMounting(state) {
  var match = TransitionGroupContext$negRescriptTransitionGroup.useContext(undefined);
  var dispatch = match[1];
  React.useEffect((function () {
          Curry._1(dispatch, /* Mounting */{
                _0: state
              });
          
        }), []);
  
}

function Transition(Props) {
  var children = Props.children;
  var match = TransitionGroupContext$negRescriptTransitionGroup.useContext(undefined);
  return Curry._1(children, match[0]);
}

var make = Transition;

exports.isMounting = isMounting;
exports.useIsMounting = useIsMounting;
exports.make = make;
/* react Not a pure module */
