// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TransitionGroupContext$negRescriptTransitionGroup = require("./TransitionGroupContext.bs.js");

var make = TransitionGroupContext$negRescriptTransitionGroup.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

exports.make = make;
exports.makeProps = makeProps;
/* make Not a pure module */
